In [2]:
#dependencies
import numpy as np
import pandas as pd
import re as regex
import io

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [ ]:
ser = pd.Series(mydict)
ser = pd.Series.to_frame(ser).reset_index()
ser

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(myarr)
ser2 = pd.Series(mylist)
df = pd.concat([ser1,ser2],axis=1)
df

0  1
0    0  a
1    1  b
2    2  c
3    3  e
4    4  d
5    5  f
6    6  g
7    7  h
8    8  i
9    9  j
10  10  k
11  11  l
12  12  m
13  13  n
14  14  o
15  15  p
16  16  q
17  17  r
18  18  s
19  19  t
20  20  u
21  21  v
22  22  w
23  23  x
24  24  y
25  25  z

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [ ]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser = pd.Series.to_frame(ser, name = "latin letters")

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
intersect = set(ser1) & set(ser2)

ser1[~ser1.isin(ser2)].dropna()

0    1
1    2
2    3
dtype: int64

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

intersect = set(ser1).symmetric_difference(set(ser2))
intersect

{1, 2, 3, 6, 7, 8}

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))
pers1 = np.percentile(ser,25)
med = np.median(ser)
pers2 = np.percentile(ser,75)
max = np.amax(ser)
print(ser)
print(pers1, med, pers2, max)

0      7.091036
1      5.120481
2      7.709646
3     12.786255
4     10.687059
5     16.766856
6     10.570202
7      8.211296
8     13.604719
9     12.725175
10    14.732281
11    11.040305
12    12.727088
13     8.979283
14     7.840268
15     7.599804
16     2.088159
17     5.272039
18    15.404366
19     2.816541
20     9.781330
21     3.143456
22     9.960709
23     8.774891
24    10.695982
dtype: float64
7.599803507934532 9.781329880469608 12.725174950820438 16.766855801550623


In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

b    5
h    5
c    5
f    4
d    4
e    3
g    3
a    1
dtype: int64

In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print(ser.value_counts())
print(ser.value_counts()[:2])


3    4
2    4
1    2
4    2
dtype: int64
3    4
2    4
dtype: int64


In [ ]:
ser = pd.Series(np.random.random(20))
result = pd.qcut(ser,10, labels = ["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"])
print(result)

0      6th
1      2nd
2      2nd
3      4th
4      1st
5     10th
6     10th
7      4th
8      9th
9      9th
10     3rd
11     7th
12     3rd
13     8th
14     1st
15     5th
16     7th
17     5th
18     6th
19     8th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']


In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))

def transform_series(x, chunk_size):
    df = pd.DataFrame()
    for i in range(chunk_size):
        df[f'column_{i+1}'] = x[i::chunk_size].reset_index(drop=True)
    return df

transformed_df = transform_series(ser, chunk_size=5)
transformed_df

column_1  column_2  column_3  column_4  column_5
0         9         3         9         4         9
1         6         5         7         6         3
2         3         4         8         4         7
3         4         2         4         2         2
4         2         8         2         8         4
5         1         4         4         6         2
6         6         7         9         8         5

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))
print(ser)
ser = pd.Series.to_numpy(ser)
np.argwhere(ser % 3 == 0)

0    3
1    7
2    4
3    1
4    2
5    5
6    2
dtype: int64


array([[0]])

In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df1 = pd.concat([ser1, ser2], axis = 1)
df2 = pd.concat([ser1,ser2],axis = 0, ignore_index=True)
print(df1)
print()
print(df2)


   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

0    0
1    1
2    2
3    3
4    4
5    a
6    b
7    c
8    d
9    e
dtype: object


In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
out = (ser2.to_numpy() == ser1.to_numpy()[:, None]).argmax(axis=0)
out

array([5, 4, 0, 8])

In [ ]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
mse1 = (np.square(truth - np.mean(truth))).mean(axis=0)
mse2 = (np.square(pred - np.mean(pred))).mean(axis=0)
mse1, mse2

(8.25, 8.776812009355508)

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
newser=ser.map(lambda x: str(x[0].upper()) + str(x[1:]))
newser

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
newser=ser.map(lambda x: len(x))
newser

0    3
1    2
2    4
3    4
dtype: int64

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
print(list(ser.diff()))
print(list(ser.diff().diff()))

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
print("Date: ", list(np.arange(1,7)))
print("Week number:", list(pd.to_datetime(ser).apply(lambda x: x.weekofyear)))
print("Day num of year:", list(pd.to_datetime(ser).apply(lambda x: x.dayofyear)))
print("Day of week:", list(pd.to_datetime(ser).apply(lambda x: x.day_name())))


Date:  [1, 2, 3, 4, 5, 6]
Week number: [53, 5, 9, 14, 19, 23]
Day num of year: [1, 33, 63, 94, 125, 157]
Day of week: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [ ]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
pd.to_datetime(ser).apply(lambda x: x.replace(day=4))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [ ]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
ser.where(ser.str.count(r'[aeiouAEIOU]')>=2).dropna()

0     Apple
1    Orange
4     Money
dtype: object

In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
print(emails[emails.map(lambda i: bool(regex.match(pattern, i)))])

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
print(weights.groupby(fruit).mean())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'apple', 'carrot', 'banana', 'banana', 'carrot', 'apple', 'banana', 'apple', 'apple']
apple     7.0
banana    4.5
carrot    4.5
dtype: float64


In [ ]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
print(sum((p - q)**2)**0.5)

18.16590212458495


In [ ]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
[idx for idx in range(1, len(ser)-1) if ser[idx-1] < ser[idx] > ser[idx+1] ]

[1, 5, 7]

In [ ]:
my_str = 'dbc deb abed gade'
my_str.replace(' ', min({elem: list(my_str).count(elem) for elem in list(my_str)}, key={elem: list(my_str).count(elem) for elem in list(my_str)}.get))

'dbccdebcabedcgade'

In [ ]:
pd.concat([pd.Series(pd.date_range(start='1/1/2000', periods = 10, freq='7D')),pd.Series(np.random.randint(10,size=10))],axis=1)

0  1
0 2000-01-01  1
1 2000-01-08  8
2 2000-01-15  5
3 2000-01-22  8
4 2000-01-29  8
5 2000-02-05  1
6 2000-02-12  2
7 2000-02-19  3
8 2000-02-26  7
9 2000-03-04  8

In [ ]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
idx = pd.date_range(ser.index.min(), ser.index.max())
ser.index = pd.DatetimeIndex(ser.index)
ser = ser.reindex(idx, method='ffill')
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64


In [ ]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
lst = list(ser.autocorr(lag=i) for i in range(1,11))
print(lst)
print("Lag having highest correlation: ",lst.index(np.max(np.array(lst))))

[0.18865556895903987, -0.05870391152298012, -0.09734473116583482, -0.32182795608935216, -0.13696573710709542, -0.012071554066367562, 0.07986427210837128, -0.30239074730410087, -0.4427499214036401, 0.34267333914301434]
Lag having highest correlation:  9


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', sep=",",skiprows=lambda i: i % 50)
df

crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1  0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2  2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3  0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4  0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   
5  0.05561  70   2.24     0  0.400  7.041  10.0  7.8278    5  358     14.8   
6  0.02899  40   1.25     0  0.429  6.939  34.5  8.7921    1  335     19.7   
7  9.91655   0  18.10     0  0.693  5.852  77.8  1.5004   24  666     20.2   
8  7.52601   0  18.10     0  0.713  6.417  98.3  2.1850   24  666     20.2   
9  0.17783   0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   

        b  lstat  medv  
0  396.90  16.20  19.4  
1  396.90   6.19  33.2  
2  351.85  21.45  15.4  
3  396.90   4.56  34.9  
4  393.74   6.56  26.2  
5  371.58   4.74  29.0  
6  389.85   5.89  26.6  
7  338.16  29.97   6.3  
8  304.21  19.31  13.0  
9  395.77  15.10  17.5

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', sep=",")
conditions = { "Low": df['medv'] < 25,"High": df['medv'] > 25,}
df['medv'] = np.select(conditions.values(), conditions.keys(), default=df['medv'])
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98   Low  
1       17.8  396.90   9.14   Low  
2       17.8  392.83   4.03  High  
3       18.7  394.63   2.94  High  
4       18.7  396.90   5.33  High  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67   Low  
502     21.0  396.90   9.08   Low  
503     21.0  396.90   5.64   Low  
504     21.0  393.45   6.48   Low  
505     21.0  396.90   7.88   Low  

[506 rows x 14 columns]

In [ ]:
L = pd.Series(range(15))
def gen_strides(a, stride_len, window_len):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, 2, 4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', sep=",",  usecols = ['crim','medv'])
df

506 2


crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', sep=",")
print(df.shape[0],df.shape[1])
print(df.dtypes)
print(df.describe())

93 27
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
       Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.1186

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
result = df.loc[df['Price'].idxmax()]
print(result)
print("This is ",result.name," row and Manufacturer, Model and Type are ",result.Manufacturer,",",result.Model,",",result.Type)

Manufacturer               Mercedes-Benz
Model                               300E
Type                             Midsize
Min.Price                           43.8
Price                               61.9
Max.Price                           80.0
MPG.city                            19.0
MPG.highway                         25.0
AirBags               Driver & Passenger
DriveTrain                          Rear
Cylinders                              6
EngineSize                           3.2
Horsepower                         217.0
RPM                               5500.0
Rev.per.mile                      2220.0
Man.trans.avail                       No
Fuel.tank.capacity                  18.5
Passengers                           5.0
Length                               NaN
Wheelbase                          110.0
Width                               69.0
Turn.circle                         37.0
Rear.seat.room                       NaN
Luggage.room                        15.0
Weight          

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.columns = df.columns.str.replace("[.]", "_", regex=True)
df.rename(columns={"Type" : "CarType"}, inplace=True)
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.isnull().values.any()

True

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.isna().sum())
print(df.isna().sum().idxmax())

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64
Luggage.room


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].median())
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9      18.80      25.0   
1           NaN   Legend  Midsize  29.200000   33.9      38.70      18.0   
2          Audi       90  Compact  25.900000   29.1      32.30      20.0   
3          Audi      100  Midsize  17.118605   37.7      44.60      19.0   
4           BMW     535i  Midsize  17.118605   30.0      19.15      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7      22.70      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0      22.40      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3      23.70      18.0   
91        Volvo      240  Compact  21.800000   22.7      23.50      21.0   
92          NaN      850  Midsize  24.800000   26.7      28.50      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price'] = df['Min.Price'].apply(lambda x: df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].apply(lambda x: df['Max.Price'].median())
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  17.118605   15.9      19.15      25.0   
1           NaN   Legend  Midsize  17.118605   33.9      19.15      18.0   
2          Audi       90  Compact  17.118605   29.1      19.15      20.0   
3          Audi      100  Midsize  17.118605   37.7      19.15      19.0   
4           BMW     535i  Midsize  17.118605   30.0      19.15      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  17.118605   19.7      19.15      17.0   
89   Volkswagen   Passat  Compact  17.118605   20.0      19.15      21.0   
90   Volkswagen  Corrado   Sporty  17.118605   23.3      19.15      18.0   
91        Volvo      240  Compact  17.118605   22.7      19.15      21.0   
92          NaN      850  Midsize  17.118605   26.7      19.15      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
a = pd.DataFrame(df['a'])

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df1 = df.reindex(columns = ['c','b','a','d','e'])
print(df1)

def swap(df,column_list, ind1, ind2):
  column_list[ind1], column_list[ind2] = column_list[ind2], column_list[ind1]
  return df.reindex(columns = column_list)

df2 = swap(df, list(df.columns), 0, 2)
print(df2)

df3 = df[sorted(df, reverse=True)]
print(df3)

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
pd.options.display.max_rows = 10
pd.options.display.max_columns = 10
df

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [ ]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
pd.reset_option('display.float_format', silent=True)
print(df)
pd.set_option('display.float_format', lambda x: '%.4f' % x)
print(df)

         random
0  1.068442e-01
1  7.808730e-03
2  5.641761e-13
3  2.739414e-05
   random
0  0.1068
1  0.0078
2  0.0000
3  0.0000


In [ ]:
df = pd.DataFrame(np.random.random(4), columns=['random'])
print(df)
pd.options.display.float_format = '{:.2%}'.format
print(df)

   random
0  0.4523
1  0.5105
2  0.0687
3  0.7735
   random
0  45.23%
1  51.05%
2   6.87%
3  77.35%


In [ ]:
pd.reset_option('^display.', silent=True)

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df1 = df['Manufacturer'][df.index % 20 == 0]
print(df1)
df2 = df['Model'][df['Model'].index % 20 == 0]
df3 = df['Type'][df.index % 20 == 0]
print(df2)
print(df3)

0        Acura
20    Chrysler
40       Honda
60     Mercury
80      Subaru
Name: Manufacturer, dtype: object
0     Integra
20    LeBaron
40    Prelude
60     Cougar
80     Loyale
Name: Model, dtype: object
0       Small
20    Compact
40     Sporty
60    Midsize
80      Small
Name: Type, dtype: object


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
newlist = ['Manufacturer','Model','Type']
for i in newlist:
  df[i] = df[i].fillna('missing')
print(df)
df.set_index(['Manufacturer','Model','Type'],drop=False)
print(len(df.index)==len(df))

   Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small       12.9       18.8
1       missing   Legend  Midsize       29.2       38.7
2          Audi       90  Compact       25.9       32.3
3          Audi      100  Midsize        NaN       44.6
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van       16.6       22.7
89   Volkswagen   Passat  Compact       17.6       22.4
90   Volkswagen  Corrado   Sporty       22.9       23.7
91        Volvo      240  Compact       21.8       23.5
92      missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]
True


In [ ]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df)
result = df['a'].argsort()[::-1][5]
print(result)

    a   b   c
0  22  12  18
1  26   1  18
2  11  28  25
3   6   8  18
4  14  11  12
5  15  25  19
6  26  25  19
7  23   4  17
8  29   4   4
9  24  19   8
7


In [ ]:
ser = pd.Series(np.random.randint(1, 100, 15))
print(ser[ser>ser.mean()][2])

In [ ]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
result = df.loc[df.sum(1)>100]
print(result)
print(result[-2:])

     0   1   2   3
0   31  23  21  20
1   12  11  27  28
2   13  29  23  17
3   24  11  22  33
4   29  21  16  24
5   29  10  15  29
6   38  37  11  11
7   10  17  19  14
8   22  22  39  19
9   36  26  38  39
10  25  20  15  14
11  19  17  39  33
12  29  37  39  14
13  13  37  12  25
14  33  24  17  38
     0   1   2   3
8   22  22  39  19
9   36  26  38  39
11  19  17  39  33
12  29  37  39  14
14  33  24  17  38
     0   1   2   3
12  29  37  39  14
14  33  24  17  38


In [ ]:
ser = pd.Series(np.logspace(-2, 2, 30))
print(ser)
ser[ser < ser.quantile(0.05)] = ser.quantile(0.05)
ser[ser > ser.quantile(0.95)] = ser.quantile(0.95)
print(ser)

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64
0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
5      0.048939
6      0.067234
7      0.092367
8      0.126896
9      0.174333
10     0.239503
11     0.329034
12     0.452035
13     0.621017
14     0.853168
15     1.172102
16     1.610262
17     2.212216
18     3.039195
19     4.175319
20     5.736153
21     7.880463
22    10.826367
23    14.873521
24    20.433597
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.87

In [ ]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df,'\n')
df = df.to_numpy().flatten()
df = df[df>=0]
result = np.array(np.take(df, sorted(np.argsort(df)[-(int(np.floor(np.sqrt(len(df))))**2):]))).reshape(int(np.floor(np.sqrt(len(df)))),int(np.floor(np.sqrt(len(df)))))
print(result)

    0   1   2   3   4   5   6   7   8   9
0   5  16  18  39  49  16  23  -1  37   8
1 -13   3   9 -19   7  12   3 -14  16  24
2  -4  16  -1  43 -17  47  11  41  31 -19
3  -4  32   4   0  -9 -13  14  32  16  -2
4  36  47  -9  26  18  48   7  35  37 -10
5 -11  45  40 -10  -9 -15  12 -10  -4  26
6  19 -10  44  -8  16  36  -2  31   4  35
7  43   9  23   2  -9  11  22  38  26  16
8  42  14   5  47  22  32  39  14  23   8
9 -20  38  -5 -19  48  12  -1  47  36  18 

[[16 18 39 49 16 23 37  8]
 [ 9  7 12 16 24 16 43 47]
 [11 41 31 32 14 32 16 36]
 [47 26 18 48  7 35 37 45]
 [40 12 26 19 44 16 36 31]
 [35 43  9 23 11 22 38 26]
 [16 42 14 47 22 32 39 14]
 [23  8 38 48 12 47 36 18]]


In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
def swap_rows(df, row1, row2):
    df.iloc[row1], df.iloc[row2] =  df.iloc[row2].copy(), df.iloc[row1].copy()
    return df

swap_rows(df, 0,1)
df

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


0   1   2   3   4
0   5   6   7   8   9
1   0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
data_rev2 = df[::-1].reset_index(drop = True)    # Reset index
print(data_rev2)

    0   1   2   3   4
0  20  21  22  23  24
1  15  16  17  18  19
2  10  11  12  13  14
3   5   6   7   8   9
4   0   1   2   3   4


In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
print(df)
df = pd.concat([pd.get_dummies(df['a'],dtype=float),df],axis=1)
df

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


0    5   10   15   20   a   b   c   d   e
0  1.0  0.0  0.0  0.0  0.0   0   1   2   3   4
1  0.0  1.0  0.0  0.0  0.0   5   6   7   8   9
2  0.0  0.0  1.0  0.0  0.0  10  11  12  13  14
3  0.0  0.0  0.0  1.0  0.0  15  16  17  18  19
4  0.0  0.0  0.0  0.0  1.0  20  21  22  23  24

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
print(df)
result = df.idxmax(axis=1).value_counts().idxmax()
result

    0   1   2   3
0  43  57  51  36
1  77  88   8  52
2  87   6  92  90
3  20  93  97  40
4  89  81  92  57
5  73   6  73  92
6   4  70  30  59
7   6  79  30  57
8  73  73  41  52
9  36   4  43   5


1

In [ ]:
#59
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(df)
distances, indices = nbrs.kneighbors(df)
df.insert(4,"nearest row",df.index[indices[:,1]],True)
df.insert(5,"distances", distances[:,1],True)
print(df.index[indices[:,1]])
df

Index(['i', 'e', 'e', 'e', 'c', 'g', 'f', 'a', 'a', 'a'], dtype='object')


p   q   r   s nearest row  distances
a  80  45  24  20           i  42.213742
b  59  76  76  96           e  47.233463
c  84  40  79  63           e  23.958297
d  34  39  55  27           e  52.163205
e  72  55  66  57           c  23.958297
f  16  44  76  76           g  32.664966
g  11  41  44  73           f  32.664966
h  36  24   2   2           a  56.435804
i  61  51   5  52           a  42.213742
j  73  93  13  13           a  50.229473

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
print(np.sort(df.corr().abs())[:,-2])

[0.85422949 0.55091051 0.42954075 0.71716197 0.63427179 0.85422949
 0.89850107 0.78808567 0.62101184 0.89850107]


In [ ]:
#61
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(df)
result = pd.concat([df.idxmax(axis=1),df.idxmin(axis=1)],axis=1)
result

    0   1   2   3   4   5   6   7   8   9
0  26  13  53  69  10  45  31  53  38  53
1  55  72  54  56  92  66  10  97  71  41
2  68   6  68  53  27  70  78  25  87  49
3  39   3  21  80  17  61  37  93  81  85
4  57  52  56  46  94   7  43  11  96   9
5  19  64  12  31  98  92  73  48  23  69
6  89  60  61  91   9  99   5  58   5  85
7  50  63  79  64  22  27   9  65  68   4


0  1
0  3  4
1  7  6
2  8  1
3  7  1
4  8  5
5  4  2
6  5  6
7  2  9

In [ ]:
#62
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(df)
df['penultimate'] = df.apply(lambda row: row.nlargest(2).values[1],axis=1)
df

    0   1   2   3   4   5   6   7   8   9
0  34  59  95   5  43  14  62  18  91  88
1  60  80  17   3   7  86  29  19  91  68
2  88  45  84  43  67  40  32  98   2  78
3  89  28  57  37  28  65  10  30  94  18
4  37  87  33  24  52  84  56  36  49  24
5  87  85  22  29  19  96  55  30  66  79
6  29  60  53  22  54  73   4  94  84  37
7  83  67  75  13  95  88  48  16  74  28


0   1   2   3   4   5   6   7   8   9  penultimate
0  34  59  95   5  43  14  62  18  91  88           91
1  60  80  17   3   7  86  29  19  91  68           86
2  88  45  84  43  67  40  32  98   2  78           88
3  89  28  57  37  28  65  10  30  94  18           89
4  37  87  33  24  52  84  56  36  49  24           84
5  87  85  22  29  19  96  55  30  66  79           87
6  29  60  53  22  54  73   4  94  84  37           84
7  83  67  75  13  95  88  48  16  74  28           88

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(df)
df1 = (df - df.mean()) / (df.std())
print(df1)
df2 = (df - df.min()) / (df.max()- df.min())
print(df2)
#another sort

    0   1   2   3   4   5   6   7   8   9
0  49  29  72  87  43  21  16  89   5  47
1  81  29  69  22  71  64  97  39  16  75
2  31  80   7  14  24   5  20  84  74  52
3  30  96  60  72  62  37  78   4   4  14
4  27  68  35  36  30  47  27  93  70  37
5   7  61  69  19  85  55  89   4  41  46
6  20  12   7  96  25   1  83  80  30  16
7   2  99  17  28  32  79  51  70  83  99
          0         1         2         3         4         5         6  \
0  0.724679 -0.923937  1.041674  1.221099 -0.150497 -0.630391 -1.253100   
1  2.004113 -0.923937  0.937506 -0.750862  1.053476  0.907584  1.185365   
2  0.004998  0.633775 -1.215286 -0.993565 -0.967478 -1.202661 -1.132682   
3 -0.034985  1.122469  0.625004  0.766031  0.666485 -0.058121  0.613379   
4 -0.154931  0.267255 -0.243057 -0.326132 -0.709484  0.299548 -0.921950   
5 -0.954577  0.053451  0.937506 -0.841876  1.655463  0.585682  0.944529   
6 -0.434807 -1.443175 -1.215286  1.494140 -0.924479 -1.345728  0.763902   
7 -1.154489  1.214099 

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
print(df)
np.fill_diagonal(np.fliplr(df), np.zeros(10))
df = np.roll(df, 0,axis=0)
print("Mean value normalize")
print(df)
np.fill_diagonal(np.fliplr(df), np.zeros(10))
print("Min max normalize")
print(df)
df = np.roll(df, 0, axis=0)
df

    0   1   2   3   4   5   6   7   8   9
0  66  68  97  86  34  64  44  58  71  64
1  85   8  14  92  75  53  67  66  28  76
2   8  58  61  74  19  38  71  13  59   3
3  62   4   9  35  89  19  50  93  87  90
4   4  20  78  57  58  26  25  17  29   2
5  75  77  89  48   3  38  75  55   3  68
6  80  80  60  92  43  75  22  78  26  78
7  95  47  68  93  99  26  54  98  16  57
8  17  13  46  28  81  24  37  66  39  22
9  67  78  21  93  35  48  98   5  25  67
[[66 68 97 86 34 64 44 58 71  0]
 [85  8 14 92 75 53 67 66  0 76]
 [ 8 58 61 74 19 38 71  0 59  3]
 [62  4  9 35 89 19  0 93 87 90]
 [ 4 20 78 57 58  0 25 17 29  2]
 [75 77 89 48  0 38 75 55  3 68]
 [80 80 60  0 43 75 22 78 26 78]
 [95 47  0 93 99 26 54 98 16 57]
 [17  0 46 28 81 24 37 66 39 22]
 [ 0 78 21 93 35 48 98  5 25 67]]
[[66 68 97 86 34 64 44 58 71  0]
 [85  8 14 92 75 53 67 66  0 76]
 [ 8 58 61 74 19 38 71  0 59  3]
 [62  4  9 35 89 19  0 93 87 90]
 [ 4 20 78 57 58  0 25 17 29  2]
 [75 77 89 48  0 38 75 55  3 68]
 [80 80 6

array([[66, 68, 97, 86, 34, 64, 44, 58, 71,  0],
       [85,  8, 14, 92, 75, 53, 67, 66,  0, 76],
       [ 8, 58, 61, 74, 19, 38, 71,  0, 59,  3],
       [62,  4,  9, 35, 89, 19,  0, 93, 87, 90],
       [ 4, 20, 78, 57, 58,  0, 25, 17, 29,  2],
       [75, 77, 89, 48,  0, 38, 75, 55,  3, 68],
       [80, 80, 60,  0, 43, 75, 22, 78, 26, 78],
       [95, 47,  0, 93, 99, 26, 54, 98, 16, 57],
       [17,  0, 46, 28, 81, 24, 37, 66, 39, 22],
       [ 0, 78, 21, 93, 35, 48, 98,  5, 25, 67]])

In [5]:
#65?
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
print(df)
np.fill_diagonal(df.values, 0)
np.fill_diagonal(np.fliplr(df.values), 0)
df

    0   1   2   3   4   5   6   7   8   9
0   5  28  33  38  37  79  75  53   1  50
1  99  25  68  81   1  17  18  93  35  20
2  95   6  35  42   6  98  29  99  40  76
3  21  47  55  21  80  23  79  96  53  44
4  49  41  77  95  80  52  90  23  40  96
5  40   3  25   9  19  60  17  58  70  22
6  19  37  79  14  62  15  67  85  42  79
7  83  91  65  23  60  40  21  15  95   5
8   4  13  58  62  87  30   9  53  91  51
9  61  48  90  97  41  53   5  99   6  31


0   1   2   3   4   5   6   7   8   9
0   0  28  33  38  37  79  75  53   1   0
1  99   0  68  81   1  17  18  93   0  20
2  95   6   0  42   6  98  29   0  40  76
3  21  47  55   0  80  23   0  96  53  44
4  49  41  77  95   0   0  90  23  40  96
5  40   3  25   9   0   0  17  58  70  22
6  19  37  79   0  62  15   0  85  42  79
7  83  91   0  23  60  40  21   0  95   5
8   4   0  58  62  87  30   9  53   0  51
9   0  48  90  97  41  53   5  99   6   0

In [14]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
new_df = pd.DataFrame(df.loc[df['col1'] == 'apple'])
new_df

col1      col2  col3
0  apple  0.419372    11
3  apple  0.112663     8
6  apple  0.602841    13

In [37]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
print(df)
print(df.loc[df['fruit'] == 'banana'])
print("Result is ",df.loc[df['fruit'] == 'banana'].nlargest(2, 'rating').min()['rating'])

    fruit    rating  price
0   apple  0.948808     10
1  banana  0.742288      9
2  orange  0.095342      2
3   apple  0.474049     12
4  banana  0.528739      7
5  orange  0.398901     14
6   apple  0.902886     11
7  banana  0.581848      1
8  orange  0.673427      5
    fruit    rating  price
1  banana  0.742288      9
4  banana  0.528739      7
7  banana  0.581848      1
Result is  0.5818475823941698


In [161]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
print(df)
new_df = df.groupby('fruit').mean().drop('rating',axis=1)
new_df

    fruit    rating  price
0   apple  0.784637      0
1  banana  0.926162      4
2  orange  0.406926     12
3   apple  0.445659     13
4  banana  0.325546      3
5  orange  0.876471      0
6   apple  0.556848      0
7  banana  0.134436     10
8  orange  0.235197     10


price
fruit           
apple   4.333333
banana  5.666667
orange  7.333333

In [65]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
print(df1)
print(df2)
pd.concat([df1,df2.rename(columns={'pazham':'fruit','kilo':'weight'})],ignore_index=True)

    fruit  weight  price
0   apple    high      3
1  banana  medium      1
2  orange     low      1
3   apple    high      2
4  banana  medium      7
5  orange     low     11
6   apple    high      4
7  banana  medium      2
8  orange     low      6
   pazham  kilo  price
0   apple  high      3
1  orange   low      4
2    pine  high      9
3   apple   low     12
4  orange  high      1
5    pine   low     12


fruit  weight  price
0    apple    high      3
1   banana  medium      1
2   orange     low      1
3    apple    high      2
4   banana  medium      7
5   orange     low     11
6    apple    high      4
7   banana  medium      2
8   orange     low      6
9    apple    high      3
10  orange     low      4
11    pine    high      9
12   apple     low     12
13  orange    high      1
14    pine     low     12

In [71]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df['a_lag1'], df['b_lead1'] = df.a.shift(1), df.b.shift(-1)
df

a   b   c   d  a_lag1  b_lead1
0  73  82  96  74     NaN     96.0
1  30  96  19   6    73.0     38.0
2  73  38  96  21    30.0     37.0
3  67  37  30  11    73.0     75.0
4  26  75  99  71    67.0      NaN

In [84]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
print(df)
new_df = df.apply(pd.value_counts).fillna(0)
result = new_df['a']+new_df['b']+new_df['c']+new_df['d']
result

   a  b  c  d
0  6  3  1  5
1  4  5  7  2
2  9  5  2  7
3  1  4  6  6
4  3  2  2  3


1    2.0
2    4.0
3    3.0
4    2.0
5    3.0
6    3.0
7    2.0
9    1.0
dtype: float64

In [155]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)
df[['0','1']] = df['row'].str.split(',',expand=True)
df[['1','2']] = df['1'].str.split('    ',expand=True)
df = df.drop('row',axis=1)
new_header = df.iloc[0]
df = df[1:]
df.columns = new_header
df

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka


0 STD        City        State
1  33     Kolkata  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka