In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA
import numpy as np
from numpy import linalg as LA
import pandas as pd

In [3]:
dataset = load_breast_cancer()

In [4]:
data_col_names = dataset.feature_names
data = dataset.data
target = dataset.target

In [5]:
def c_pca(initial_data, pс_number: int):
    df = pd.DataFrame(data=initial_data, columns=data_col_names)
    df = df - df.mean()
    numpy_arr = pd.DataFrame(df).to_numpy()
    cov_matr = np.cov(numpy_arr, rowvar=False)
    eigenvalues, eigenvectors = LA.eig(cov_matr)
    sorted_indexes = np.argsort(-eigenvalues)
    pc_indexes = sorted_indexes[:pс_number]
    n_principal_components = eigenvectors[:, pc_indexes]
    dotted_data = np.dot(numpy_arr, n_principal_components)
    return dotted_data

In [6]:
def skl_pca(initial_data, pс_number: int):
    X = np.array(data)
    pca = PCA(n_components=pс_number)
    pca.fit(X)
    return pca.transform(data)

In [7]:
skl_pca(data, 2)

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [8]:
skl_pca(data, 3)

array([[1160.1425737 , -293.91754364,   48.57839763],
       [1269.12244319,   15.63018184,  -35.39453423],
       [ 995.79388896,   39.15674324,   -1.70975298],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718],
       [1124.85811531,   34.12922497,  -19.74208742],
       [-771.52762188,  -88.64310636,   23.88903189]])

In [9]:
skl_pca(data, 4)

array([[1160.1425737 , -293.91754364,   48.57839763,   -8.71197531],
       [1269.12244319,   15.63018184,  -35.39453423,   17.86128323],
       [ 995.79388896,   39.15674324,   -1.70975298,    4.1993401 ],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718,   -9.77188104],
       [1124.85811531,   34.12922497,  -19.74208742,  -23.66088144],
       [-771.52762188,  -88.64310636,   23.88903189,    2.54724855]])

In [10]:
c_pca(data, 2)

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [11]:
c_pca(data, 3)

array([[1160.1425737 , -293.91754364,   48.57839763],
       [1269.12244319,   15.63018184,  -35.39453423],
       [ 995.79388896,   39.15674324,   -1.70975298],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718],
       [1124.85811531,   34.12922497,  -19.74208742],
       [-771.52762188,  -88.64310636,   23.88903189]])

In [12]:
c_pca(data, 4)

array([[1160.1425737 , -293.91754364,   48.57839763,   -8.71197531],
       [1269.12244319,   15.63018184,  -35.39453423,   17.86128323],
       [ 995.79388896,   39.15674324,   -1.70975298,    4.1993401 ],
       ...,
       [ 314.50175618,   47.55352518,  -10.44240718,   -9.77188104],
       [1124.85811531,   34.12922497,  -19.74208742,  -23.66088144],
       [-771.52762188,  -88.64310636,   23.88903189,    2.54724855]])